name:                path-extra
version:             0.2.0
github:              "athanclark/path-extra"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "Copyright (c) 2023 Athan Clark"
category:            System, Filesystem, Web
synopsis:            URLs without host information

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/athanclark/path-extra#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.8 && < 5
- attoparsec
- path >= 0.9
- text

library:
  source-dirs: src

tests:
  path-extra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - path-extra
    - path
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - quickcheck-instances
