name:                path-extra
version:             0.2.0
github:              "athanclark/path-extra"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "Copyright (c) 2018 Athan Clark"
category:            System, Filesystem, Web
synopsis:            URLs without host information

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/localcooking-db#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.8 && < 5
- attoparsec
- path
- text

library:
  source-dirs: src

tests:
  path-extra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - path-extra
    - path
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - quickcheck-instances
